### ISSUE TITLE
`session` static property missing from Model

### ISSUE THREAD

**Issue by ahutchings** [tomasz-zablocki/redux-orm-types#19]
The `session` static property is missing from the Model class, which causes the following code to raise a TS error - `Property 'session' does not exist on type 'typeof Node'`.

```typescript

  /**
   * Clones the node.
   */
  public clone(): Node {
    const {id, ...attributes} = this.ref;

    return this.getClass().session.Node.create({
      ...attributes,
    });
  }

```

The `session` getter is implemented here:
https://github.com/redux-orm/redux-orm/blob/3efec435039a56476da6872f623972021bd94703/src/Model.js#L207

**Comment by tomasz-zablocki** [comment]
@ahutchings, as you can see [here](https://github.com/redux-orm/redux-orm/blob/3efec435039a56476da6872f623972021bd94703/src/Model.js#L204), the static `session` property of `Model` class is private, which is why it's not present in the type declarations. 

You can however achieve the same result as of the clone method by changing it to the following:

Change this:
```typescript
  /**
   * Clones the node.
   */
  public clone(): Node {
    const {id, ...attributes} = this.ref;

    return this.getClass().session.Node.create({
      ...attributes,
    });
  }
```

to this:
```typescript
  /**
   * Clones the node.
   */
  public clone(): Node {
    const {id, ...attributes} = this.ref;

    return this.getClass().create({
      ...attributes,
    });
  }
```

This is due to `this.getClass().session.Node` and `this.getClass()` called from within `Node` return the same object. 

Let me know if this solves your issue.

**Comment by ahutchings** [comment]
Thanks, that nicely solves the use case of cloning. I have some additional use cases where I need to create instances of other model types from a model instance in the current session. I didn't realize the `session` property was private, so this may not be a use case that redux-orm intends to support. Because of that, I'm fine with closing this issue unless you think this is a valid use-case that should be pursued in the redux-orm repo.

For now, I implemented a couple of utility functions to encapsulate session access from model classes and instances. With this I can maintain type-safety without peppering @ts-ignore comments everywhere session is accessed.

```typescript
function getSession<M extends Model>(model: M): MySession {
  return getClassSession(model.getClass());
}

function getClassSession<M extends Model>(
  model: ReturnType<M['getClass']>,
): MySession {
  // @ts-ignore `session` is private. See https://github.com/redux-orm/redux-orm/blob/3efec435039a56476da6872f623972021bd94703/src/Model.js#L204
  return model.session;
}
```

**Comment by tomasz-zablocki** [comment]
> I have some additional use cases where I need to create instances of other model types from a model instance in the current session. I didn't realize the `session` property was private, so this may not be a use case that redux-orm intends to support. Because of that, I'm fine with closing this issue unless you think this is a valid use-case that should be pursued in the redux-orm repo.

Accessing session from `Model` instances is most likely not supported. For instance, in the [primer project](https://github.com/tommikaikkonen/redux-orm-primer#writing-reducers) the original author of redux-orm states: 

> You usually won't need the Session instance, but you can access and query other models through the Session instance (for example, you can access the Tag model through session.Tag), but modifying other model's data is not recommended nor supported.

This might be old stuff, but I don't think it has changed. 

If you're using a per-model-static-reducer function approach, the `Session` is your last parameter. You can use it to read data, but creating and modifying other models then the current one is not supported.

If you're using a standalone reducer then you can (or have to) access the `Session` instance like [here](https://github.com/redux-orm/redux-orm#redux-integration). 

Additionally for many-to-many relations you should use `add`, `remove` or `clear` methods present on `many` field related `QuerySet` properties.
