### ISSUE TITLE
Types appear to be broken as of redux-orm v0.14.0

### ISSUE THREAD

**Issue by hdh3000** [tomasz-zablocki/redux-orm-types#24]
See this issue here for a summary of what I am hitting: https://github.com/redux-orm/redux-orm/issues/331

Basically [PR #257](https://github.com/redux-orm/redux-orm/commit/bcbbb151465de28ada1a50536915912caaa7c4e7) in the redux-orm repo introduced the idea of a `stateSelector` as an option to the ORM constructor + additional breaking changes to the `createSelector` api. These type definitions then fell behind.

It seems like a relatively simple fix, but I just downloaded this library today to play with it (the core concept is amazing), and so am not totally familiar with what the change would require.

**Comment by pocheptsov** [comment]
^ Added in https://github.com/tomasz-zablocki/redux-orm-types/tree/0.15 branch. You can use it with:
```
# package.json
{
"devDependencies": {
  ...
  "@types/redux-orm": "tomasz-zablocki/redux-orm-types#0.15"
  ...
}
}
```

**Comment by hdh3000** [comment]
Thanks!
